### ISSUE TITLE
TF issue

### ISSUE THREAD

**Issue by philippeller** [oval-group/ali-g#3] opened 2021-02-24 09:41 UTC
Hi,

I just read your nice paper and wanted to try out the `alig` optimizer for my own applications. I use TF 2.4.1 on GPUs, and run into some cryptic error messages when trying it with a very simple dense NN.

Any help would be appreciated!

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    869       # This is the first call of __call__, so we have to initialize.
    870       initializers = []
--> 871       self._initialize(args, kwds, add_initializers_to=initializers)
    872     finally:
    873       # At this point we know that the initialization is complete (or less

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    723     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    724     self._concrete_stateful_fn = (
--> 725         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    726             *args, **kwds))
    727 

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2967       args, kwargs = None, None
   2968     with self._lock:
-> 2969       graph_function, _ = self._maybe_define_function(args, kwargs)
   2970     return graph_function
   2971 

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3359 
   3360           self._function_cache.missed.add(call_context_key)
-> 3361           graph_function = self._create_graph_function(args, kwargs)
   3362           self._function_cache.primary[cache_key] = graph_function
   3363 

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3194     arg_names = base_arg_names + missing_arg_names
   3195     graph_function = ConcreteFunction(
-> 3196         func_graph_module.func_graph_from_py_func(
   3197             self._name,
   3198             self._python_function,

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    988         _, original_func = tf_decorator.unwrap(python_func)
    989 
--> 990       func_outputs = python_func(*func_args, **func_kwargs)
    991 
    992       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    632             xla_context.Exit()
    633         else:
--> 634           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    635         return out
    636 

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

ValueError: in user code:

    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:757 train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v1.py:784 minimize
        self.apply_gradients(grads_and_vars)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v1.py:787 apply_gradients
        self.optimizer.apply_gradients(grads_and_vars, global_step=self.iterations)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/training/optimizer.py:600 apply_gradients
        self._prepare()
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/training/gradient_descent.py:81 _prepare
        self._learning_rate_tensor = ops.convert_to_tensor(
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1540 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:339 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:264 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:281 _constant_impl
        tensor_util.make_tensor_proto(
    /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py:445 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.```

**Comment by lberrada** [comment] 2021-03-06 11:09
Hi, it seems that this issue is due to some breaking changes in tensorflow since the ALI-G code was released. Could you try running your code with the following Keras implementation of ALI-G? If that doesn't work, can you provide a minimal example that reproduces the issue?

```python
class AliG(tf.keras.optimizers.SGD):
    """Optimizer that implements the AliG algorithm.
    """

    def __init__(self, max_lr=None, momentum=0.0, name="AliG", eps=1e-5):
        super(AliG, self).__init__(
            learning_rate=1.0,
            name=name,
            momentum=momentum,
            nesterov=bool(momentum),
          )
        self._set_hyper("max_lr", max_lr if max_lr is not None else 0.0)
        self._set_hyper("eps", eps)

    def minimize(self, loss, var_list, grad_loss=None, name=None, tape=None):
        # first part of method is identical to tf
        grads_and_vars = self._compute_gradients(
            loss, var_list=var_list, tape=tape, grad_loss=grad_loss)

        # compute learning-rate here
        grad_sqrd_norm = sum(tf.norm(grad) ** 2 for grad, _ in grads_and_vars)
        learning_rate = loss / (grad_sqrd_norm + self._get_hyper("eps"))

        max_lr = self._get_hyper("max_lr")

        learning_rate = tf.cond(
            max_lr > 0.0,
            lambda: tf.clip_by_value(
                learning_rate,
                clip_value_min=0,
                clip_value_max=max_lr),
            lambda: learning_rate,
        )

        grads_and_vars = [(g * learning_rate, v) for g, v in grads_and_vars]

        return self.apply_gradients(grads_and_vars, name=name)
```

**Comment by philippeller** [comment] 2021-03-06 16:54
Thank you so much for the answer!

I can confirm that the above does work for me, however I had to add some explicit casting to double precision of the hyper parameters, i.e.
```python
        self._set_hyper("max_lr", np.float64(max_lr) if max_lr is not None else np.float64(0.0))
        self._set_hyper("eps", np.float64(eps))
```

Without I got exceptions. This might be due to me setting `tf.keras.backend.set_floatx('float64')` in my example

**Comment by lberrada** [comment] 2021-03-06 18:19
Perfect, closing this then.

**Closed as completed by lberrada** 2021-03-06 18:19 UTC
